apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  template:
    spec:
      repository: perezjoseph/Gestion-inmobiliaria
      labels:
        - arc-runner
        - arc-runner-dind
        - arc-deploy
      dockerEnabled: true
      dockerMTU: 1450
      imagePullPolicy: IfNotPresent
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.10
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - arc-systems.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
          - name: timeout
            value: "3"
          - name: attempts
            value: "3"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    actions-runner: ""
                topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "1"
          memory: 3Gi
        limits:
          cpu: "2"
          memory: 5Gi
      volumeMounts:
        - name: cargo-cache
          mountPath: /home/runner/.cargo/registry
          subPath: registry
        - name: cargo-cache
          mountPath: /home/runner/.cargo/git
          subPath: git
        - name: sccache
          mountPath: /home/runner/.sccache
        - name: cargo-target
          mountPath: /home/runner/_work/_target
      volumes:
        - name: cargo-cache
          nfs:
            server: 192.168.88.22
            path: /volume1/k3s-cache/cargo-cache
        - name: sccache
          nfs:
            server: 192.168.88.22
            path: /volume1/k3s-cache/sccache
        - name: cargo-target
          nfs:
            server: 192.168.88.22
            path: /volume1/k3s-cache/cargo-target
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: arc-runner-dind
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - Gestion-inmobiliaria
