apiVersion: v1
kind: Pod
metadata:
  name: reboot-inference
  namespace: realestate
spec:
  nodeSelector:
    kubernetes.io/hostname: inference
  hostPID: true
  tolerations:
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule
  restartPolicy: Never
  containers:
    - name: reboot
      image: fedora:44
      command:
        - nsenter
        - -t
        - "1"
        - -m
        - --
        - systemctl
        - reboot
      securityContext:
        privileged: true
