apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  actions-runner: ""
              topologyKey: kubernetes.io/hostname
            weight: 100
      dockerEnabled: true
      dockerMTU: 1450
      imagePullPolicy: IfNotPresent
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.43.0.10
          - 8.8.8.8
          - 1.1.1.1
        searches:
          - arc-systems.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
          - name: timeout
            value: "3"
          - name: attempts
            value: "3"
      labels:
      - arc-runner
      - arc-runner-dind
      - arc-deploy
      repository: perezjoseph/Gestion-inmobiliaria
      resources:
        limits:
          cpu: "2"
          memory: 5Gi
        requests:
          cpu: "1"
          memory: 3Gi
      volumeMounts:
      - mountPath: /home/runner/.cargo/registry
        name: cargo-cache
        subPath: registry
      - mountPath: /home/runner/.cargo/git
        name: cargo-cache
        subPath: git
      - mountPath: /home/runner/.sccache
        name: sccache
      - mountPath: /home/runner/_work/_target
        name: cargo-target
      volumes:
      - name: cargo-cache
        nfs:
          path: /volume1/docker/k3s-cache/cargo-cache
          server: 192.168.88.22
      - name: sccache
        nfs:
          path: /volume1/docker/k3s-cache/sccache
          server: 192.168.88.22
      - name: cargo-target
        nfs:
          path: /volume1/docker/k3s-cache/cargo-target
          server: 192.168.88.22
