sonar.projectKey=gestion-inmobiliaria
sonar.projectName=Gestion Inmobiliaria

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/target/**,**/dist/**,**/node_modules/**,**/*.generated.*

sonar.cpd.minimumTokens=50
sonar.sourceEncoding=UTF-8
