apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vllm-scaledobject
  namespace: realestate
spec:
  scaleTargetRef:
    name: vllm
  minReplicaCount: 0
  maxReplicaCount: 1
  idleReplicaCount: 0
  cooldownPeriod: 3600
  pollingInterval: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.monitoring.svc.cluster.local:9090
        query: sum(rate(vllm:request_success_total[5m])) OR vector(0)
        threshold: "0.001"
        activationThreshold: "0.001"
      metricType: AverageValue
  fallback:
    failureThreshold: 5
    replicas: 0
