{
 "title": "Intel XPU Manager v2",
 "tags": [
  "xpum",
  "gpu",
  "intel"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pci_bdf) (hw_gpu_utilization_ratio{job=\"xpumanager\"})",
     "legendFormat": "{{pci_bdf}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pci_bdf) (hw_gpu_utilization_ratio{job=\"xpumanager\"})",
     "legendFormat": "{{pci_bdf}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "hw_frequency_hertz{aggregation=\"avg\", job=\"xpumanager\"}",
     "legendFormat": "{{hw_frequency_domain}}"
    }
   ]
  },
  {
   "title": "GPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_frequency_hertz{aggregation=\"avg\", job=\"xpumanager\"}",
     "legendFormat": "{{hw_frequency_domain}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\", job=\"xpumanager\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "min: GPU"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\", job=\"xpumanager\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "max: GPU"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"max\", job=\"xpumanager\", hw_sensor_location=\"gpu\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"min\", job=\"xpumanager\", hw_sensor_location=\"memory\"}",
     "legendFormat": "min: Memory"
    },
    {
     "expr": "hw_temperature_celsius{statistic=\"max\", job=\"xpumanager\", hw_sensor_location=\"memory\"}",
     "legendFormat": "max: Memory"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_temperature_celsius{statistic=\"max\", job=\"xpumanager\", hw_sensor_location=\"memory\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "hw_power_watts{job=\"xpumanager\"}",
     "legendFormat": "{{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_power_watts{job=\"xpumanager\"}",
     "legendFormat": "{{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "hw_energy_joules_total{job=\"xpumanager\"}",
     "legendFormat": "{{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_energy_joules_total{job=\"xpumanager\"}",
     "legendFormat": "{{hw_sensor_location}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_usage_bytes{job=\"xpumanager\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "hw_memory_size_bytes{job=\"xpumanager\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_io_bytes_total{network_io_direction=\"receive\", job=\"xpumanager\"}",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Mem Read Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_memory_io_bytes_total{network_io_direction=\"receive\", job=\"xpumanager\"}[10s])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Memory Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_memory_io_bytes_total{network_io_direction=\"transmit\", job=\"xpumanager\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Mem Write Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_memory_io_bytes_total{network_io_direction=\"transmit\", job=\"xpumanager\"}[10s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_memory_usage_bytes{job=\"xpumanager\"} / hw_memory_size_bytes{job=\"xpumanager\"}",
     "legendFormat": "VRAM %"
    }
   ]
  },
  {
   "title": "Memory Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_memory_bandwidth_utilization_ratio{job=\"xpumanager\"}",
     "legendFormat": "Mem BW"
    }
   ]
  },
  {
   "title": "Engine Group Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pci_bdf, hw_gpu_task) (hw_gpu_utilization_ratio{job=\"xpumanager\"})",
     "legendFormat": "{{hw_gpu_task}}"
    }
   ]
  },
  {
   "title": "Per Engine Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "hw_gpu_utilization_ratio{job=\"xpumanager\"}",
     "legendFormat": "{{hw_name}}"
    }
   ]
  },
  {
   "title": "PCIe Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_gpu_io_bytes_total{network_io_direction=\"receive\", job=\"xpumanager\"}",
     "legendFormat": "PCIe Read"
    }
   ]
  },
  {
   "title": "PCIe Read Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_gpu_io_bytes_total{network_io_direction=\"receive\", job=\"xpumanager\"}[10s])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "PCIe Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "hw_gpu_io_bytes_total{network_io_direction=\"transmit\", job=\"xpumanager\"}",
     "legendFormat": "PCIe Write"
    }
   ]
  },
  {
   "title": "PCIe Write Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(hw_gpu_io_bytes_total{network_io_direction=\"transmit\", job=\"xpumanager\"}[10s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "GPU Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hw_gpu_info{job=\"xpumanager\"}",
     "legendFormat": "{{hw_model}}"
    }
   ]
  }
 ]
}