pub mod auditoria;
pub mod auth;
pub mod background_jobs;
pub mod configuracion;
pub mod contratos;
pub mod dashboard;
pub mod documento_editor;
pub mod documentos;
pub mod gastos;
pub mod importacion;
pub mod inquilinos;
pub mod invitaciones;
pub mod mantenimiento;
pub mod notificaciones;
pub mod ocr_client;
pub mod ocr_mapping;
#[cfg(test)]
mod ocr_mapping_pbt;
#[cfg(test)]
mod ocr_mapping_tests;
pub mod ocr_preview;
pub mod organizaciones;
pub mod pago_generacion;
pub mod pagos;
pub mod perfil;
pub mod plantillas;
pub mod propiedades;
pub mod recargos;
pub mod recibos;
pub mod reportes;
pub mod unidades;
pub mod usuarios;
pub mod validacion_fiscal;
pub mod validation;
