# docker-mailserver environment configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-env
  namespace: mail
data:
  OVERRIDE_HOSTNAME: mail.myhomeva.us
  POSTMASTER_ADDRESS: postmaster@myhomeva.us
  TLS_LEVEL: modern
  SSL_TYPE: ""
  ENABLE_RSPAMD: "1"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "1"
  FAIL2BAN_BLOCKTYPE: drop
  POSTSCREEN_ACTION: drop
  SPOOF_PROTECTION: "1"
  ENABLE_OPENDKIM: "0"
  ENABLE_OPENDMARC: "0"
  ENABLE_POLICYD_SPF: "0"
  MOVE_SPAM_TO_JUNK: "1"
  ONE_DIR: "1"
  POSTFIX_INET_PROTOCOLS: ipv4
  SUPERVISOR_LOGLEVEL: warn
  LOG_LEVEL: info
