pub mod auditoria;
pub mod contratos;
pub mod dashboard;
pub mod gastos;
pub mod importar;
pub mod inquilinos;
pub mod login;
pub mod mantenimiento;
mod page_helpers;
pub mod pagos;
pub mod perfil;
pub mod propiedades;
pub mod registro;
pub mod reportes;
pub mod usuarios;
