apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  template:
    spec:
      repository: perezjoseph/Gestion-inmobiliaria
      labels:
        - arc-runner-dind
      dockerEnabled: true
      imagePullPolicy: IfNotPresent
      nodeSelector:
        role: desktop
      resources:
        requests:
          cpu: "3"
          memory: 2Gi
        limits:
          cpu: "3"
          memory: 6Gi
      volumeMounts:
        - name: cargo-cache
          mountPath: /home/runner/.cargo/registry
          subPath: registry
        - name: cargo-cache
          mountPath: /home/runner/.cargo/git
          subPath: git
        - name: sccache
          mountPath: /home/runner/.sccache
        - name: cargo-target
          mountPath: /home/runner/_work/_target
      volumes:
        - name: cargo-cache
          hostPath:
            path: /opt/cargo-cache
            type: DirectoryOrCreate
        - name: sccache
          hostPath:
            path: /opt/sccache
            type: DirectoryOrCreate
        - name: cargo-target
          hostPath:
            path: /opt/cargo-target
            type: DirectoryOrCreate
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: arc-runner-dind
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - Gestion-inmobiliaria
