apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  template:
    spec:
      repository: perezjoseph/Gestion-inmobiliaria
      labels:
        - arc-runner
        - arc-runner-dind
        - arc-deploy
      dockerEnabled: true
      imagePullPolicy: IfNotPresent
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    actions-runner: ""
                topologyKey: kubernetes.io/hostname
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "2"
          memory: 3Gi
      volumeMounts:
        - name: cargo-cache
          mountPath: /home/runner/.cargo/registry
          subPath: registry
        - name: cargo-cache
          mountPath: /home/runner/.cargo/git
          subPath: git
        - name: sccache
          mountPath: /home/runner/.sccache
        - name: cargo-target
          mountPath: /home/runner/_work/_target
      volumes:
        - name: cargo-cache
          hostPath:
            path: /opt/cargo-cache
            type: DirectoryOrCreate
        - name: sccache
          hostPath:
            path: /opt/sccache
            type: DirectoryOrCreate
        - name: cargo-target
          hostPath:
            path: /opt/cargo-target
            type: DirectoryOrCreate
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: arc-runner-dind
  namespace: arc-systems
spec:
  scaleTargetRef:
    kind: RunnerDeployment
    name: arc-runner-dind
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - Gestion-inmobiliaria
