apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-deploy
  namespace: arc-systems
spec:
  replicas: 1
  template:
    spec:
      repository: perezjoseph/Gestion-inmobiliaria
      labels:
        - arc-deploy
      nodeSelector:
        role: server
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 250m
          memory: 1Gi
      volumeMounts:
        - name: cargo-cache
          mountPath: /home/runner/.cargo/registry
          subPath: registry
        - name: cargo-cache
          mountPath: /home/runner/.cargo/git
          subPath: git
        - name: sccache
          mountPath: /home/runner/.sccache
      volumes:
        - name: cargo-cache
          hostPath:
            path: /opt/cargo-cache
            type: DirectoryOrCreate
        - name: sccache
          hostPath:
            path: /opt/sccache
            type: DirectoryOrCreate
