#!/usr/bin/env bash
source "$(dirname "$0")/autofix-stack-classify.sh"

classify_stack "test.rs"
classify_stack "baileys-service/src/index.ts"
classify_stack "android/app/Main.kt"
classify_stack "ocr-service/main.py"
classify_stack "infra/Dockerfile"
classify_stack "backend.Dockerfile"
classify_stack "infra/k8s/app/deploy.yml"
classify_stack "scripts/build.sh"
classify_stack "README.md"

echo "---"
sensor_pattern "rust"
sensor_pattern "ts"
sensor_pattern "kotlin"
sensor_pattern "python"
sensor_pattern "docker"
sensor_pattern "k8s"
sensor_pattern "shell"
sensor_pattern "none"
